### ISSUE TITLE
Crash when using SocketActivityHierarchyServer with requestWindowFeature()

### ISSUE THREAD

**Issue by eliasbagley** [JakeWharton/u2020#243]
Hi,

This isn't a bug with u2020 per se, but with the SocketActivityHierarchyServer which I pulled from this project.

I get the following crash when including both `SocketActivityHierarchyServer` and `requestWindowFeature(Window.FEATURE_NO_TITLE);`

I've pushed a minimal project which reproduces this crash: https://github.com/eliasbagley/socketservertest

Application subclass:

```
public class MyApp extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        Timber.plant(new Timber.DebugTree());
        registerActivityLifecycleCallbacks(new SocketActivityHierarchyServer());
    }
}
```

Activity:
```
public class MainActivity extends Activity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        requestWindowFeature(Window.FEATURE_NO_TITLE);

        setContentView(R.layout.activity_main);
    }
}
```

Stacktrace:

```
EXCEPTION: main
                                                                                  Process: com.eliasbagley.socketservertest, PID: 10186
                                                                                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.eliasbagley.socketservertest/com.eliasbagley.socketservertest.MainActivity}: android.util.AndroidRuntimeException: requestFeature() must be called before adding content
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3119)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3218)
                                                                                      at android.app.ActivityThread.access$1000(ActivityThread.java:198)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1676)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:145)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6837)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
                                                                                   Caused by: android.util.AndroidRuntimeException: requestFeature() must be called before adding content
                                                                                      at com.android.internal.policy.impl.PhoneWindow.requestFeature(PhoneWindow.java:374)
                                                                                      at android.app.Activity.requestWindowFeature(Activity.java:3869)
                                                                                      at com.eliasbagley.socketservertest.MainActivity.onCreate(MainActivity.java:13)
                                                                                      at android.app.Activity.performCreate(Activity.java:6500)
                                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1120)
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3072)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3218) 
                                                                                      at android.app.ActivityThread.access$1000(ActivityThread.java:198) 
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1676) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                      at android.os.Looper.loop(Looper.java:145) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6837) 
                                                                                      a
```

**Comment by JakeWharton** [comment]
Call `requestWindowFeature` before calling `super.onCreate` or change your `SocketActivityHierarchyServer` to post to the main thread before calling `getWindow()` and setting itself up.
