### ISSUE TITLE
StrictMode policy violation

### ISSUE THREAD

**Issue by dongyuan** [JakeWharton/u2020#245]
It's best practice to keep disk and network operations off the main thread. Once the StrictMode was added in this project.

@Override public void onCreate() {
    super.onCreate();
    if (BuildConfig.DEBUG) {
      StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder().detectDiskReads()
          .detectDiskWrites()
          .detectNetwork()
          .penaltyLog()
          .build());
    }

    AndroidThreeTen.init(this);

You can see few violations in the log.
StrictMode policy violation; ~duration=202 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=23 violation=2
 at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1137)
 at libcore.io.BlockGuardOs.fstat(BlockGuardOs.java:132)
 at java.io.RandomAccessFile.length(RandomAccessFile.java:237)
 at java.util.zip.ZipFile$RAFStream.<init>(ZipFile.java:477)
 at java.util.zip.ZipFile.readCentralDir(ZipFile.java:434)
 at java.util.zip.ZipFile.<init>(ZipFile.java:163)
 at java.util.zip.ZipFile.<init>(ZipFile.java:119)
 at dalvik.system.DexPathList$Element.maybeInit(DexPathList.java:431)
 at dalvik.system.DexPathList$Element.findResource(DexPathList.java:445)
 at dalvik.system.DexPathList.findResources(DexPathList.java:361)
 at dalvik.system.BaseDexClassLoader.findResources(BaseDexClassLoader.java:72)
 at java.lang.ClassLoader.getResources(ClassLoader.java:425)
 at java.util.ServiceLoader.internalLoad(ServiceLoader.java:129)
 at java.util.ServiceLoader.reload(ServiceLoader.java:93)
 at java.util.ServiceLoader.<init>(ServiceLoader.java:86)
 at java.util.ServiceLoader.load(ServiceLoader.java:122)
 at org.threeten.bp.zone.ZoneRulesProvider.<clinit>(ZoneRulesProvider.java:84)
 at com.jakewharton.threetenabp.AndroidThreeTen.init(AndroidThreeTen.java:22)
 at com.jakewharton.u2020.U2020App.onCreate(U2020App.java:33)
 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4566)
 at android.app.ActivityThread.access$1500(ActivityThread.java:148)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:135)
 at android.app.ActivityThread.main(ActivityThread.java:5272)
 at java.lang.reflect.Method.invoke(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:372)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)

**Comment by IgorGanapolsky** [comment]
Log says ` ~duration=202 ms`.  What's an acceptable duration?

**Comment by dongyuan** [comment]
It doesn't matter. we shouldn't run the disk options on the main thread.

**Comment by JakeWharton** [comment]
It's far from that simple. Just set up strict mode after this call or don't use ThreeTenABP.

Filed https://github.com/JakeWharton/ThreeTenABP/issues/23 but unlikely I'll get around to it any time soon.
