### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by hafsalrahman** [JakeWharton/u2020#255]
W/dalvikvm: threadid=1: calling UncaughtExceptionHandler
06-26 22:57:32.976 20121-20121/com.jakewharton.u2020.internal.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                      Process: com.jakewharton.u2020.internal.debug, PID: 20121
                                                                                      java.lang.VerifyError: com/jakewharton/u2020/data/IntentFactory$
                                                                                          at com.jakewharton.u2020.data.IntentFactory$$Lambda$1.createUrlIntent(Unknown Source)
                                                                                          at com.jakewharton.u2020.data.DebugIntentFactory.createUrlIntent(DebugIntentFactory.java:24)
                                                                                          at com.jakewharton.u2020.ui.trending.TrendingView.onRepositoryClick(TrendingView.java:187)
                                                                                          at com.jakewharton.u2020.ui.trending.TrendingAdapter$ViewHolder.lambda$new$0(TrendingAdapter.java:61)
                                                                                          at com.jakewharton.u2020.ui.trending.TrendingAdapter$ViewHolder$$Lambda$1.onClick(Unknown Source)
                                                                                          at android.view.View.performClick(View.java:4463)
                                                                                          at android.view.View$PerformClick.run(View.java:18770)
                                                                                          at android.os.Handler.handleCallback(Handler.java:808)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                                          at android.os.Looper.loop(Looper.java:193)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:5333)
                                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
                                                                                          at dalvik.system.NativeStart.main(Native Method)

**Comment by JakeWharton** [comment]
If you scroll higher up in the logs you can see the cause of the verification error. Otherwise it looks like a bad incremental Retrolambda build. Doing a clean build should fix the problem.
